version: '3'
services:
    frontend:
        restart: always
        build: ./frontend
        ports: 
            - '8082:3000'
    backend:
        restart: always
        build: ./backend
        ports: 
            - '8081:8080'
    postgres:
        restart: always
        image: postgres:9.6.19-alpine
        ports: 
            - '8083:5432'
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ps_data:/var/lib/postgres/data
volumes:
    ps_data:
